#!/bin/bash

orders=( 0 0 1 3 10 33 155 1043 12345 274667 )
type=simple

for ordering in random incdeg decdeg inorder
do
  for n in {2..6}
  do
    src_folder=/home/matthew/1_Project/Mathematics/GraphTheory/small-graph-colouring/graphs/$n
    x=${orders[$n]}
    for i in `seq 1 $x`;\
       do\
        ccli greedy --type=$type --ordering=$ordering $src_folder/$i.dimacs;\
       done

    sed -n 's/CLRS \([0-9]*\) [A-Z a-z = 0-9 .]*/\1/p' $src_folder/*.dimacs.res\
       | paste -s -d"+"\
       | bc\
       | tee output_$type\_$ordering\_$n.txt

    rm $src_folder/*.dimacs.res
  done
done
